filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/auth.log
    - /var/log/syslog
    #- /var/log/*.log
  fields:
    document_type: syslog
  fields_under_root: true


output.logstash:
  enabled: true
  hosts: ["elk.mccorkle.co:5044"]
  # bulk_max_size: 1024
  
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-public.crt"]

#shipper:
logging.tofiles: true
logging.files:
  rotateeverybytes: 10485760 # = 10MB

